(()=>{"use strict";
const S={mode:"countdown",status:"idle",duration:300000,remaining:300000,elapsed:0,endAt:0,last:0,laps:[],raf:0,sound:true,effects:true,customOpen:false};
const $=id=>document.getElementById(id);
const pad=n=>String(Math.floor(n)).padStart(2,"0");
const fmt=(ms,cs=false)=>{ms=Math.max(0,ms);const total=Math.floor(ms/1000),h=Math.floor(total/3600),m=Math.floor(total%3600/60),s=total%60;return cs?(pad(Math.floor(total/60))+":"+pad(s)+"."+pad(ms%1000/10)):((h?pad(h)+":":"")+pad(m)+":"+pad(s));};
function current(){if(S.status!=="running")return S.mode==="countdown"?S.remaining:S.elapsed;const now=Date.now();return S.mode==="countdown"?Math.max(0,S.endAt-now):S.elapsed+(now-S.last)}
function setStatus(status){S.status=status;const root=$("clockModule");if(!root)return;root.classList.toggle("clock-running",status==="running"&&S.effects);root.classList.toggle("clock-paused",status==="paused");root.classList.toggle("clock-completed",status==="completed"&&S.effects);root.classList.toggle("clock-low",S.mode==="countdown"&&S.duration>0&&current()/S.duration<=.2&&status==="running"&&S.effects);$("clockStatusText").textContent=status==="running"?"Đang chạy":status==="paused"?"Đã tạm dừng":status==="completed"?"Hoàn thành!":"Sẵn sàng bắt đầu!";$("clockStatus").className="clock-status "+status}
function render(){const root=$("clockModule");if(!root)return;const value=current();$("clockCountdownDisplay").hidden=S.mode!=="countdown";$("clockStopwatchDisplay").hidden=S.mode!=="stopwatch";$("clockCountdownControls").hidden=S.mode!=="countdown";$("clockStopwatchControls").hidden=S.mode!=="stopwatch";$("clockCountdownDisplay").textContent=fmt(value);$("clockStopwatchDisplay").textContent=fmt(value,true);root.querySelectorAll("[data-clock-mode]").forEach(b=>b.classList.toggle("active",b.dataset.clockMode===S.mode));$("clockStart").hidden=S.status==="running"||S.status==="completed";$("clockPause").hidden=S.status!=="running";$("clockReset").disabled=S.status==="idle";$("clockLap").hidden=!(S.mode==="stopwatch"&&S.status==="running");const pct=S.mode==="countdown"&&S.duration?Math.max(0,Math.min(100,value/S.duration*100)):0;$("clockProgressBar").style.width=(S.mode==="stopwatch"?"100":pct)+"%";$("clockProgressTimi").style.left=(S.mode==="stopwatch"?"100":pct)+"%";$("clockProgressBar").style.background=S.mode==="countdown"?(pct<=10?"linear-gradient(90deg,#ed6c78,#f39a78)":pct<=20?"linear-gradient(90deg,#ffc83d,#f5a623)":"linear-gradient(90deg,#40d27e,#24b968)"):"linear-gradient(90deg,#2f80ed,#62a7ff)";$("clockCustomPanel").hidden=!S.customOpen;renderMessage();renderLaps();setStatus(S.status)}
function renderMessage(){let msg="“Cùng cố gắng để đạt được mục tiêu nhé!”";if(S.status==="running"&&S.mode==="countdown"){const pct=S.duration?current()/S.duration:1;msg=pct<=.1?"“Sắp hết giờ rồi! Cố lên!”":pct<=.2?"“Sắp hoàn thành rồi!”":"“Cố lên các bạn ơi!”"}if(S.status==="completed")msg="“Tuyệt vời! Chúng ta đã hoàn thành!”";if(S.status==="paused")msg="“Đang tạm dừng. Khi sẵn sàng, tiếp tục nhé!”";$("timiSpeech").textContent=msg.replace(/[“”]/g,"");$("timiMessage").textContent=msg}
function renderLaps(){const box=$("clockLapList");if(!box)return;if(!S.laps.length){box.innerHTML='<div class="clock-empty">Chưa có mốc thời gian. Nhấn “Ghi mốc” khi cần.</div>';return}box.innerHTML=S.laps.map((x,i)=>'<div class="clock-lap-row"><strong>LAP '+(i+1)+'</strong><span>'+fmt(x.total,true)+'</span><small>+ '+fmt(x.lap,true)+'</small></div>').join("")}
function tick(){if(S.status!=="running")return;if(S.mode==="countdown"){S.remaining=Math.max(0,S.endAt-Date.now());if(S.remaining<=0){S.remaining=0;S.status="completed";cancelAnimationFrame(S.raf);render();if(S.sound)beep();return}}else{const now=Date.now();S.elapsed+=now-S.last;S.last=now}render();S.raf=requestAnimationFrame(tick)}
function start(){if(S.mode==="countdown"){if(S.status==="idle"){S.duration=readInputs();S.remaining=S.duration}if(S.status==="completed"){S.remaining=S.duration}if(S.remaining<=0)return;S.endAt=Date.now()+S.remaining}else{if(S.status==="idle"||S.status==="completed"){S.elapsed=0;S.laps=[]}S.last=Date.now()}S.status="running";cancelAnimationFrame(S.raf);S.raf=requestAnimationFrame(tick);render()}
function pause(){if(S.status!=="running")return;if(S.mode==="countdown")S.remaining=Math.max(0,S.endAt-Date.now());else{const now=Date.now();S.elapsed+=now-S.last}S.status="paused";cancelAnimationFrame(S.raf);render()}
function reset(){cancelAnimationFrame(S.raf);S.status="idle";S.laps=[];if(S.mode==="countdown"){S.duration=readInputs();if(!S.duration)S.duration=300000;S.remaining=S.duration}else S.elapsed=0;render()}
function readInputs(){const h=Math.max(0,+$("clockHours").value||0),m=Math.min(59,Math.max(0,+$("clockMinutes").value||0)),s=Math.min(59,Math.max(0,+$("clockSeconds").value||0));return(h*3600+m*60+s)*1000}
function applyPreset(sec){cancelAnimationFrame(S.raf);S.mode="countdown";S.status="idle";S.duration=sec*1000;S.remaining=S.duration;$("clockHours").value=Math.floor(sec/3600);$("clockMinutes").value=Math.floor(sec%3600/60);$("clockSeconds").value=sec%60;document.querySelectorAll("[data-seconds]").forEach(b=>b.classList.toggle("selected",+b.dataset.seconds===sec));render()}
function beep(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=880;g.gain.value=.08;o.connect(g);g.connect(c.destination);o.start();setTimeout(()=>{o.stop();c.close()},500)}catch(e){}}
function focusMode(){const root=$("clockModule");root.classList.toggle("clock-focus");document.body.classList.toggle("clock-focus-body",root.classList.contains("clock-focus"));if(root.classList.contains("clock-focus"))document.documentElement.requestFullscreen?.().catch(()=>{});else document.exitFullscreen?.().catch(()=>{});}
window.ClockModule={open(){if(typeof showPage==="function")showPage("clock");render()}};
document.addEventListener("click",e=>{const mode=e.target.closest("[data-clock-mode]");if(mode){cancelAnimationFrame(S.raf);S.mode=mode.dataset.clockMode;S.status="idle";S.laps=[];render();return}if(e.target.closest("#clockStart"))start();if(e.target.closest("#clockPause"))pause();if(e.target.closest("#clockReset"))reset();if(e.target.closest("#clockLap")&&S.status==="running"){const total=current(),prev=S.laps.length?S.laps[S.laps.length-1].total:0;S.laps.push({total,lap:total-prev});render()}const preset=e.target.closest("[data-seconds]");if(preset)applyPreset(+preset.dataset.seconds);if(e.target.closest("#clockCustomToggle")){S.customOpen=!S.customOpen;render()}if(e.target.closest("#clockApply")){S.duration=readInputs();if(S.duration>0){S.remaining=S.duration;S.status="idle";S.customOpen=false;document.querySelectorAll("[data-seconds]").forEach(b=>b.classList.remove("selected"));render()}}if(e.target.closest("#clockFullscreen"))focusMode()});
document.addEventListener("change",e=>{if(e.target.id==="clockSound")S.sound=e.target.checked;if(e.target.id==="clockEffects")S.effects=e.target.checked;render()});
document.addEventListener("keydown",e=>{if(["INPUT","TEXTAREA"].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if(k===" "){e.preventDefault();S.status==="running"?pause():start()}if(k==="r")reset();if(k==="f")focusMode();if(k==="l"&&S.mode==="stopwatch"&&S.status==="running"){$("clockLap").click()}});
document.addEventListener("DOMContentLoaded",()=>{S.duration=300000;S.remaining=300000;render()});
})();